CREATE DATABASE IF NOT EXISTS `CHESS`;
CREATE DATABASE IF NOT EXISTS `TEST`;

CREATE TABLE `CHESS`.`CHESS_GAME`
(
    `GAME_ID`    int         NOT NULL AUTO_INCREMENT,
    `STATE`      varchar(10) NOT NULL,
    `CREATED_AT` datetime    NOT NULL,
    PRIMARY KEY (`GAME_ID`)
);
CREATE TABLE `TEST`.`CHESS_GAME` LIKE `CHESS`.`CHESS_GAME`;

CREATE TABLE `CHESS`.`PIECE`
(
    `PIECE_ID` int          NOT NULL AUTO_INCREMENT,
    `TYPE`     varchar(255) NOT NULL,
    `COLOR`    varchar(255) NOT NULL,
    `GAME_ID`  int          NOT NULL,
    PRIMARY KEY (`PIECE_ID`),
    FOREIGN KEY (`GAME_ID`) REFERENCES `CHESS_GAME` (`GAME_ID`)
);
CREATE TABLE `TEST`.`PIECE` LIKE `CHESS`.`PIECE`;

CREATE TABLE `CHESS`.`POSITION`
(
    `POSITION_ID` int NOT NULL AUTO_INCREMENT,
    `FILE`        int NOT NULL,
    `RANK`        int NOT NULL,
    `PIECE_ID`    int NOT NULL,
    PRIMARY KEY (`POSITION_ID`),
    FOREIGN KEY (`PIECE_ID`) REFERENCES `PIECE` (`PIECE_ID`)
);
CREATE TABLE `TEST`.`POSITION` LIKE `CHESS`.`POSITION`;
