CREATE DATABASE IF NOT EXISTS `CHESS`;
CREATE DATABASE IF NOT EXISTS `TEST`;

CREATE TABLE `CHESS`.`CHESS_GAME`
(
    `GAME_ID`    INT         NOT NULL AUTO_INCREMENT,
    `STATE`      VARCHAR(10) NOT NULL,
    `CREATED_AT` DATETIME    NOT NULL,
    PRIMARY KEY (`GAME_ID`)
);
CREATE TABLE `TEST`.`CHESS_GAME` LIKE `CHESS`.`CHESS_GAME`;

CREATE TABLE `CHESS`.`PIECE`
(
    `PIECE_ID` INT         NOT NULL AUTO_INCREMENT,
    `GAME_ID`  INT         NOT NULL,
    `TYPE`     VARCHAR(10) NOT NULL,
    `COLOR`    VARCHAR(10) NOT NULL,
    `FILE`     INT         NOT NULL,
    `RANK`     INT         NOT NULL,
    PRIMARY KEY (`PIECE_ID`, `GAME_ID`),
    FOREIGN KEY (`GAME_ID`) REFERENCES `CHESS_GAME` (`GAME_ID`) ON DELETE CASCADE
);
CREATE TABLE `TEST`.`PIECE` LIKE `CHESS`.`PIECE`;
